
---
#数据库开关 true打开 false关闭
datasource:
 enabled: false



---
#拦截器开关 true打开 false关闭
filter:
  path:          #路径
    enabled: true
  auth:          #认证
    enabled: false

---
#时间日期转换开关 true打开 false关闭
dataConvert:
 enabled: false




---
#注册服务地址设置
eureka:
  client:
    fetch-registry: true #从服务端获得注册信息
    service-url:
        defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.registerInfo}:6898/eureka,http://${security.user.name}:${security.user.password}@${eureka.instance.registerInfo}:6899/eureka

  instance:
#    registerInfo: localhost
    registerInfo: 47.97.174.183
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    ip-address: 47.97.174.183

---
#关闭mq检查
management:
  health:
    rabbit:
      enabled: false

---
#redis配置
spring:
  redis:
    host: 47.97.174.183
    port: 8048
    database: 1
    password: etongjin



---
#mq 配置
mq:
  host: 47.97.174.183
  port: 5672
  userName: etongjin
  userPass: 123456

---
#spring security的api验证开关
spring.security.enabled: true

---
#security的开启认证
security:
  user:
    name: test
    password: test

---
#关闭spring的datasource初始化
spring.datasource.initialize: false


---
#设置spring atomikos的日志
spring:
  jta:
    log-dir: ${java.io.tmpdir}/${random.uuid}


---
#关闭jackson的默认输出null
spring:
  jackson:
    default-property-inclusion: non_null

---
#zookeeper的服务器地址 多个用,分开
zookeeper:
  serverList: 47.97.174.183:2181


---
#打开数据库配置
open.datasource : false
flyway.enabled: false

---
#是否打开验证频率拦截
verityLimeter.enabled: false

---
#验证码认证拦截的前缀
verify.limiter.rate.referer:  etongjin.net

---
#是否开启druid的监控平台 true打开 false不开启
druid.monitor.enabled: false

---
#是否打开自动生成sql的任务 true打开 false不打开
auto.init.sql.enabled: false