spring:
  application:
    name: ribbon
server:
  port: 8069
eureka:
  client:
    service-url:
        defaultZone: http://${eureka.instance.hostname}:8068/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true




