spring:
  application:
    name: consul
  cloud:
    consul:
      host: 192.168.12.128
      port: 8500
      discovery:
        health-check-path: /health
        health-check-interval: 15s
        instance-id: springConsul
server:
  port: 8073
#eureka:
#  client:
#    service-url:
#        defaultZone: http://${eureka.instance.hostname}:8068/eureka
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
##开启hystrix fegin 的
#feign.hystrix.enabled: true





