spring:
  application:
    name: eureka-server
server:
  port: 8011
eureka:
  client:
#    register-with-eureka: false #声明不在Eureka服务注册自己
#    fetch-registry: false
    service-url:
        defaultZone: http://${eureka.instance.hostname}:8012/eureka #如果是多个 则用,分开 注册是他人的地址
  instance:
    hostname: localhost
#    prefer-ip-address: true




