language: java
sudo: false

jdk:
- oraclejdk8
- openjdk7

install:
- mvn clean install -DskipTests=false -Dmaven.javadoc.skip=false -B -V

script:
- sh ./check_format.sh

after_success:
- mvn clean test cobertura:cobertura coveralls:report
