spring:
  application:
    name: eureka-server
server:
  port: 8012
eureka:
  client:
#    register-with-eureka: false #声明不在Eureka服务注册自己
#    fetch-registry: false
    service-url:
        defaultZone: http://${eureka.instance.hostname}:8011/eureka
  instance:
    hostname: localhost
#    prefer-ip-address: true




