spring:
  application:
    name: spring_data_jpa
  jpa:
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: none
  datasource:
      platform: h2
      schema: classpath:schema.sql
      data: classpath:data.sql
      url: jdbc:h2:~/test
#      username: admin
#      password: admin
      driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

server:
  port: 8076